apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-task-config
  namespace: ai-task-platform
data:
  MONGO_URI: mongodb://mongo:27017/ai-task-platform
  REDIS_URL: redis://redis:6379
  FRONTEND_URL: http://ai-task-platform.local
  NODE_ENV: production
